# Generated by Django 2.2 on 2023-08-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.IntegerField(max_length=5),
        ),
    ]
